# Generated by Django 6.0.2 on 2026-02-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='app_bundle_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
