# Generated by Django 6.0.2 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_api", "0002_mobiledevice_app_bundle_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermobilepreference",
            name="area_text_coloring_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usermobilepreference",
            name="personal_area_text_color",
            field=models.CharField(default="#86efac", max_length=7),
        ),
        migrations.AddField(
            model_name="usermobilepreference",
            name="work_area_text_color",
            field=models.CharField(default="#93c5fd", max_length=7),
        ),
    ]
