# Generated by Django 6.0.2 on 2026-02-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_cloud_processing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
