# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


def backfill_task_positions(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Organization = apps.get_model("core", "Organization")

    for organization in Organization.objects.all().iterator():
        ordered = list(
            Task.objects.filter(organization_id=organization.id)
            .order_by("created_at", "id")
            .only("id", "position")
        )
        for index, task in enumerate(ordered, start=1):
            task.position = index
        if ordered:
            Task.objects.bulk_update(ordered, ["position"])


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_allow_cloud_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_task_positions, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["organization", "position"], name="tasks_task_organiz_81029d_idx"),
        ),
    ]
