# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
