# Generated by Django 6.0.2 on 2026-02-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_hash_inbound_ingest_tokens'),
        ('tasks', '0005_task_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChangeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('archived', 'Archived')], max_length=32)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_change_events', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'id'], name='tasks_taskc_organiz_a8058a_idx')],
            },
        ),
    ]
