# Generated by Django 6.0.2 on 2026-02-13 23:13

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('suggest_metadata', 'Suggest Metadata'), ('embed_task', 'Embed Task'), ('weekly_review', 'Weekly Review'), ('dedupe_check', 'Dedupe Check')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('provider_used', models.CharField(choices=[('local', 'Local'), ('cloud', 'Cloud')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='core.organization')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_summaries', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_json', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField()),
                ('provider_used', models.CharField(max_length=16)),
                ('model_name', models.CharField(max_length=255)),
                ('model_version', models.CharField(blank=True, max_length=255)),
                ('input_hash', models.CharField(max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('provider_used', models.CharField(max_length=16)),
                ('model_name', models.CharField(max_length=255)),
                ('model_version', models.CharField(blank=True, max_length=255)),
                ('embedding_dimensions', models.IntegerField()),
                ('input_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'model_name', 'input_hash'), name='task_embedding_task_model_input_hash_uniq'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task', 'model_name'), name='task_embedding_one_active_per_task_model')],
            },
        ),
    ]
