# Generated by Django 6.0.2 on 2026-02-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_cloud_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='redact_sensitive_patterns',
            field=models.BooleanField(default=False),
        ),
    ]
