# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_organization_allow_cloud_ai_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="inbound_email_address",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="inbound_email_token",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
