# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_organization_inbound_email_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="inbound_email_whitelist",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
