# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_organization_inbound_email_whitelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="gmail_oauth_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="gmail_oauth_refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="inbound_email_provider",
            field=models.CharField(
                choices=[("webhook", "Webhook"), ("gmail_oauth", "Gmail OAuth")],
                default="webhook",
                max_length=32,
            ),
        ),
    ]
