# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_organization_inbound_email_oauth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="imap_folder",
            field=models.CharField(default="INBOX", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_mark_seen_on_success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_password",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_port",
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_provider",
            field=models.CharField(blank=True, default="auto", max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_search_criteria",
            field=models.CharField(default="UNSEEN", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_use_ssl",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="imap_username",
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
