# Generated by Django 6.0.2 on 2026-02-15

from django.db import migrations


def encrypt_org_external_credentials(apps, schema_editor):
    from core.crypto import encrypt_secret, is_encrypted_secret

    Organization = apps.get_model("core", "Organization")
    queryset = Organization.objects.exclude(gmail_oauth_refresh_token="").exclude(gmail_oauth_refresh_token__isnull=True)
    for organization in queryset.iterator():
        raw_value = str(organization.gmail_oauth_refresh_token or "")
        if not raw_value or is_encrypted_secret(raw_value):
            continue
        organization.gmail_oauth_refresh_token = encrypt_secret(raw_value)
        organization.save(update_fields=["gmail_oauth_refresh_token"])

    queryset = Organization.objects.exclude(imap_password="").exclude(imap_password__isnull=True)
    for organization in queryset.iterator():
        raw_value = str(organization.imap_password or "")
        if not raw_value or is_encrypted_secret(raw_value):
            continue
        organization.imap_password = encrypt_secret(raw_value)
        organization.save(update_fields=["imap_password"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_organization_imap_settings"),
    ]

    operations = [
        migrations.RunPython(encrypt_org_external_credentials, migrations.RunPython.noop),
    ]

