# Generated by Django 6.0.2 on 2026-02-15

from django.db import migrations


def hash_existing_inbound_ingest_tokens(apps, schema_editor):
    from core.security import INBOUND_TOKEN_HASH_PREFIX, hash_inbound_ingest_token

    Organization = apps.get_model("core", "Organization")
    queryset = Organization.objects.exclude(inbound_email_token="").exclude(inbound_email_token__isnull=True)
    for organization in queryset.iterator():
        raw_value = str(organization.inbound_email_token or "")
        if not raw_value:
            continue
        if raw_value.startswith(INBOUND_TOKEN_HASH_PREFIX):
            continue
        organization.inbound_email_token = hash_inbound_ingest_token(raw_value)
        organization.save(update_fields=["inbound_email_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_organization_encrypt_external_credentials"),
    ]

    operations = [
        migrations.RunPython(hash_existing_inbound_ingest_tokens, migrations.RunPython.noop),
    ]

